apiVersion: v1
kind: Service
metadata:
  name: genai-backend
spec:
  selector:
    app: genai-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500  # Optional: fixed NodePort
  type: ClusterIP