apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-backend
spec:
  podSelector:
    matchLabels:
      app: genai-backend
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: genai-frontend